package jh.hw;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-02T10:12:54.080-04:00
 * Generated source version: 3.5.2
 */
public final class CalculatorSoap_CalculatorSoap_Client {
    private static final Logger LOGGER = LoggerFactory.getLogger(CalculatorSoap_CalculatorSoap_Client.class);
    private static final QName SERVICE_NAME = new QName("http://hw.jh/", "Calculator");

    private CalculatorSoap_CalculatorSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Calculator.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                LOGGER.error(e.getMessage(), e);
            }
        }

        Calculator ss = new Calculator(wsdlURL, SERVICE_NAME);
        CalculatorSoap port = ss.getCalculatorSoap();

        int a = 100;
        int b = 10;

        try {
            test(String.format("%d + %d", a, b), a + b, port.add(a, b));
            test(String.format("%d - %d", a, b), a - b, port.subtract(a, b));
            test(String.format("%d / %d", a, b), a / b, port.divide(a, b));
            test(String.format("%d * %d", a, b), a * b, port.multiply(a, b));
        } catch (Exception e) {
            LOGGER.error(e.getMessage(), e);
        }
        System.exit(0);
    }

    private static void test(String testName, int expected, int actual) {
        if (expected == actual) {
            LOGGER.info("Test {} SUCCESS!", testName);
        } else {
            LOGGER.error("Test {} FAILURE!\n\texpected: {}\n\tactual: {}", testName, expected, actual);
        }
    }
}