package jh.hw;

import org.apache.cxf.ext.logging.LoggingFeature;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-02T09:59:51.883-04:00
 * Generated source version: 3.5.2
 */
public class CalculatorSoap_CalculatorSoap_Server {
    private static final Logger LOGGER = LoggerFactory.getLogger(CalculatorSoap_CalculatorSoap_Server.class);

    protected CalculatorSoap_CalculatorSoap_Server() throws java.lang.Exception {
        Object implementor = new CalculatorSoapImpl();
        String address = "http://localhost:8080/Calculator";
        LOGGER.info("Starting Server - {}", address);
        Endpoint.publish(address, implementor, new LoggingFeature());
    }

    public static void main(String args[]) throws java.lang.Exception {
        new CalculatorSoap_CalculatorSoap_Server();
        LOGGER.info("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        LOGGER.info("Server exiting");
        System.exit(0);
    }
}